### ISSUE TITLE
window capture source change to browser source

### ISSUE THREAD

**Issue by codefz840** [mrayhanhakim/mappool-generator#3]
https://puu.sh/E00v3/a4c999b084.png
https://puu.sh/E00v8/c5bbe57129.png
https://puu.sh/E00vc/b66014cf56.png

**Comment by reykim7854** [comment]
@NotPeOpLe Thank you for suggesting this method, but I need to change some stuff a bit to make things work on local device when using the browser source. Before I update the readme, do you have any other suggestion for this one issue?

**Comment by reykim7854** [comment]
I'll close this since I've updated it
