### ISSUE TITLE
the website isn't loading

### ISSUE THREAD

**Issue by D2SDarius** [mrayhanhakim/mappool-generator#4]
![ttyrbrtu](https://user-images.githubusercontent.com/101285104/175958204-9ca4746e-8ac9-497e-8b70-2a5ea77624e5.png)

**Comment by reykim7854** [comment]
@D2SDarius thank you for posting this issue, the url moved to this one [reykim7854.github.io/mappool-generator](https://reykim7854.github.io/mappool-generator)
